name: winmd
description: Inspect and generate Windows Metadata (.winmd) files based on the
  ECMA-335 standard.
version: 7.0.0-wip
repository: https://github.com/halildurmus/winmd
issue_tracker: https://github.com/halildurmus/winmd/issues

topics:
  - winmd
  - windows
  - metadata

environment:
  sdk: ^3.8.0-0

platforms:
  linux:
  macos:
  windows:

dependencies:
  archive: ^4.0.7
  ffi: ^2.1.4
  logging: ^1.3.0
  meta: ^1.16.0
  nuget: ^0.2.0
  path: ^1.9.1

dev_dependencies:
  checks: ^0.3.0
  halildurmus_lints: ^1.0.0
  hooks:
    git:
      url: https://github.com/halildurmus/workflows.git
      path: packages/hooks
  test: ^1.25.15
