name: winmd
description: A Dart package for working with Windows Metadata (.winmd) files.
version: 5.0.4-wip
repository: https://github.com/halildurmus/winmd
issue_tracker: https://github.com/halildurmus/winmd/issues

topics:
  - winmd
  - windows
  - metadata

environment:
  sdk: ^3.5.0

platforms:
  windows:

dependencies:
  archive: ^3.6.1
  ffi: ^2.1.3
  nuget: ^0.1.1
  path: ^1.9.0
  win32: ^5.5.4
  win32_registry: ^1.1.5

dev_dependencies:
  checks: ^0.3.0
  lints: ^5.0.0
  test: ^1.25.8
