name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      # We want to see the results on stable even if main fails (and vice
      # versa). This prevents one failure from stopping the entire run.
      fail-fast: false
      matrix:
        sdk: [stable, beta, dev]
    uses: halildurmus/halildurmus/.github/workflows/dart_package.yml@main
    with:
      analyze_directories: example lib test
      dart_sdk: ${{ matrix.sdk }}
      run_tests: ${{ matrix.sdk != 'dev' }}
      runs_on: windows-latest
      upload_coverage: ${{ matrix.sdk == 'dev' }}
