name: Examples

on:
  pull_request:
    paths:
      - .github/workflows/examples.yml
      - example/**
      - lib/**
      - analysis_options.yaml
      - pubspec.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/examples.yml
      - example/**
      - lib/**
      - analysis_options.yaml
      - pubspec.yaml

jobs:
  build:
    uses: halildurmus/workflows/.github/workflows/dart.yml@main
    with:
      analyze_directories: example
      dart_sdk: main # TODO: Remove this when 3.8 is stable
      format_directories: example
      run_tests: false
